### ISSUE TITLE
Error 'KotlinSourceSet with name 'commonMain' not found' when upgrading non-KMP project to Mockative 3

### ISSUE THREAD

**Issue by riQQ** [mockative/mockative#135]
With Mockative 2 a normal Android project was working just fine. With Mockative 3, the new plugin doesn't work. This is not documented in the [migration guide](https://github.com/mockative/mockative/blob/884f7b19aea31e3932b7bc4f7123a3ca226b3973/wiki/MIGRATING-TO-3.md). Is there any way to make this work for non-KMP projects?

```
An exception occurred applying plugin request [id: 'io.mockative', version: '3.0.0']
> Failed to apply plugin 'io.mockative'.
   > KotlinSourceSet with name 'commonMain' not found.
```

```
Caused by: org.gradle.api.UnknownDomainObjectException: KotlinSourceSet with name 'commonMain' not found.
	at org.gradle.api.internal.DefaultNamedDomainObjectCollection.createNotFoundException(DefaultNamedDomainObjectCollection.java:529)
	at org.gradle.api.internal.DefaultNamedDomainObjectCollection.getByName(DefaultNamedDomainObjectCollection.java:358)
	at org.gradle.api.internal.DefaultNamedDomainObjectCollection.getByName(DefaultNamedDomainObjectCollection.java:371)
	at io.mockative.MockativePlugin.apply(MockativePlugin.kt:55)
	at io.mockative.MockativePlugin.apply(MockativePlugin.kt:11)
	at org.gradle.api.internal.plugins.ImperativeOnlyPluginTarget.applyImperative(ImperativeOnlyPluginTarget.java:43)
<...>
```

https://github.com/mockative/mockative/blob/845a5aad25586ec2a91b2b3de05f5a4799ff9719/mockative-plugin/src/main/kotlin/io/mockative/MockativePlugin.kt#L54-L59

**Comment by Nillerr** [comment]
Hi @riQQ!

It's funny. I have never considered Mockative a contender for non-KMP projects, given the JVM ecosystem already has massively popular frameworks like MockK.

I'll have a look at supporting JVM-only projects since I don't think it will require significant changes.
