### ISSUE TITLE
Mocking not working

### ISSUE THREAD

**Issue by Nailik** [mockative/mockative#31]
I try to mock an expect/actual class that implements MultiDexApplication on Android.

   ```
 @Mock
  val application = mock(classOf<Application>())

  init {
        given(application).invocation { applicationContext }
            .thenReturn(ApplicationProvider.getApplicationContext())
}
```

When i try to run the code it says that no mock was generated but there is no more info about why and how to fix it.

```
A mock for the type Application was not generated.

    Make sure the property holding the mock is annotated with @Mock:

        @Mock
        private val myMock = mock(classOf<Application>())
    

io.mockative.NoSuchMockError: A mock for the type Application was not generated.

    Make sure the property holding the mock is annotated with @Mock:

        @Mock
        private val myMock = mock(classOf<Application>())
    

	at app//io.mockative.MocksKt.mock(Mocks.kt:17)
```

**Comment by Nillerr** [comment]
Hi @Nailik 

Thanks for reporting this issue.

I have just released version `1.2.0` of Mockative, which features a complete rewrite of the code generation using [KotlinPoet](https://square.github.io/kotlinpoet/). I included code to verify the case using `expect/actual` interfaces, which appear to work, although I did not include adding the `actual` modifier to the generated interfaces.

Please try version `1.2.0` and let me know if the problem remains, in which case I'll make sure the code generator includes `actual` modifiers for applicable generated interfaces.

**Comment by Nillerr** [comment]
Hi @Nailik 

I discovered an issue in `1.2.0` causing the generated code to be invalid. I have resolved this issue in `1.2.1`, which is on its way out.

**Comment by Nillerr** [comment]
Hi again @Nailik 

The reason you're not seeing any mock generated is because Mockative is only capable of generating mocks for `interface`s, while you appear to be attempting to mock an `open class`, and there just hasn't been enough demand for implementing mock code generation for `open class`es yet.

**Comment by tbuschto** [comment]
So if my coder under test consumes instances of an external class I have no way to give it a mock?

**Comment by androideo** [comment]
I am receiving the same error. 
Version: 1.2.3 (also 1.2.6 tested)

I am mocking an Interface, not the implementation. 
I have still one problem, that is not similiar to the documenation. I was not able to import this plugin 

>     id("com.google.devtools.ksp")


Stacktrace:
`io.mockative.NoSuchMockError: A mock for the type IRSAEncryptionService was not generated.

    Make sure the property holding the mock is annotated with @Mock:

        @Mock
        private val myMock = mock(classOf<IRSAEncryptionService>())
    

	at app//io.mockative.MocksKt.mock(Mocks.kt:17)
	at app//de.trinamix.nirs.ssf.CommonGreetingTest.<init>(commonTest.kt:16)
	at java.base@11.0.12/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base@11.0.12/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base@11.0.12/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base@11.0.12/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at app//org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:250)
	at app//org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:260)
	at app//org.junit.runners.BlockJUnit4ClassRunner$2.runReflectiveCall(BlockJUnit4ClassRunner.java:309)
	at app//org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at app//org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:306)
	at app//org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at app//org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at app//org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at app//org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at app//org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at app//org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at app//org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at app//org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at app//org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at app//org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at app//org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at java.base@11.0.12/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@11.0.12/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base@11.0.12/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@11.0.12/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)`

**Comment by Nillerr** [comment]
Hi @androideo

You mention that you're not able to import the [KSP](https://github.com/google/ksp) plugin. Without the KSP plugin you will not be able to use Mockative. Please ensure you can import the KSP plugin first, e.g. by reading through [KSP quickstart | Kotlin](https://kotlinlang.org/docs/ksp-quickstart.html#use-your-own-processor-in-a-project).

**Comment by androideo** [comment]
Hi @Nillerr 

I was able to import the KSP library by adding the following lines to my build.gradle. 

```
dependencies {
    ...
    testImplementation("com.google.devtools.ksp:symbol-processing-api:1.6.21-1.0.6")
    ...
}
```
KSP quickstart does not help me, since I want to use your processor and not my own processor in my project. Or am I thinking wrong here?

**Comment by Nillerr** [comment]
You don't need to "import" the KSP _library_. You need to import the KSP _plugin_.

Which errors are you seeing when you've added ths KSP plugin to your **build.gradle** file?

```kotlin
plugins {
    id("com.google.devtools.ksp")
}
```

**Comment by androideo** [comment]
Thanks for the support. It is working now.
I had to explictly name the version:

> id("com.google.devtools.ksp") version "1.6.21-1.0.6"
