### ISSUE TITLE
Unable to understand this error stacktrace 

### ISSUE THREAD

**Issue by findjigar** [mockative/mockative#66]
Suddenly I'm getting this error in a test that's using Mockative. I'm not being able to decide what's causing it.

```
 [ERROR] [org.gradle.api.Task] e: [ksp] java.lang.IllegalStateException: Required value was null.
        at com.squareup.kotlinpoet.ksp.UtilsKt.toClassNameInternal(utils.kt:63)
        at com.squareup.kotlinpoet.ksp.KsClassDeclarationsKt.toClassName(ksClassDeclarations.kt:24)
        at io.mockative.kotlinpoet.KSType_KotlinPoetKt.toTypeNameMockative(KSType.KotlinPoet.kt:55)
        at io.mockative.kotlinpoet.KSType_KotlinPoetKt.toTypeNameMockative(KSType.KotlinPoet.kt:97)
        at io.mockative.kotlinpoet.ProcessableFunction_KotlinPoetKt.buildParameterSpecs(ProcessableFunction.KotlinPoet.kt:58)
        at io.mockative.kotlinpoet.ProcessableFunction_KotlinPoetKt.buildFunSpec(ProcessableFunction.KotlinPoet.kt:18)
        at io.mockative.kotlinpoet.ProcessableType_KotlinPoetKt.buildFunSpecs(ProcessableType.KotlinPoet.kt:81)
        at io.mockative.kotlinpoet.ProcessableType_KotlinPoetKt.buildMockTypeSpec(ProcessableType.KotlinPoet.kt:49)
        at io.mockative.MockativeSymbolProcessor.process(MockativeSymbolProcessor.kt:33)
```

Any hint or direction to look into would help. Thanks!

- Mockative 1.4.0
- Kotlin 1.8.10

**Comment by findjigar** [comment]
Resolved it. It was a transitive dependency issue.
