### ISSUE TITLE
Failure to get class name during code generation on some Android source sets

### ISSUE THREAD

**Issue by vitorhugods** [mockative/mockative#97]
Starting on Mockative `2.2.0`, I'm facing this issue when running `kspDebugAndroidTestKotlinAndroid`.

My guess is that it was introduced in #94, as this same task was running successfully in our codebase during `2.1.0` and #94 seems to be the biggest change around this area since then.

```
> Task :logic:kspDebugAndroidTestKotlinAndroid FAILED
e: [ksp] java.lang.IllegalStateException: Required value was null.
	at com.squareup.kotlinpoet.ksp.UtilsKt.toClassNameInternal(utils.kt:63)
	at com.squareup.kotlinpoet.ksp.KsClassDeclarationsKt.toClassName(KsClassDeclarations.kt:23)
	at io.mockative.ProcessableType$Companion.fromDeclaration(ProcessableType.kt:82)
	at io.mockative.ProcessableType$Companion.fromResolver(ProcessableType.kt:143)
	at io.mockative.MockativeSymbolProcessor.process(MockativeSymbolProcessor.kt:25)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$8$1.invoke(KotlinSymbolProcessingExtension.kt:310)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$8$1.invoke(KotlinSymbolProcessingExtension.kt:308)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.handleException(KotlinSymbolProcessingExtension.kt:414)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.doAnalysis(KotlinSymbolProcessingExtension.kt:308)
```

I am trying to get more information about it. I'm not sure what is the edge case I'm falling into at the moment, as it doesn't seem to have affected Mockative's `:shared:kspDebugAndroidTestKotlinAndroid` for example.

**Comment by Nillerr** [comment]
Good catch, and thank you for debugging the issue @vitorhugods! I will add a nice error for these cases.
